# Generated by Django 2.2.11 on 2020-06-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datacompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
