# Generated by Django 2.2.11 on 2020-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='project/img/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
